### ISSUE TITLE
script标签上的data-*属性添加不上。

### ISSUE THREAD

**Issue by sunnyxujian** [ahwgs/vite-plugin-html-config#10]
## 插件配置：
```js
htmlPlugin({
    headScripts: [
        {
            src: '/gis/static/js/5.4.0/yunli-map.js',
            'data-map': true,
        },
    ],
})
```
## 编译结果：
![image](https://user-images.githubusercontent.com/24877853/197100792-1f0bebcc-833b-4a2e-a3c7-056324a6a867.png)
少了`data-map`属性。
我发现`ejs`编译的html模板也有这样的问题。不清楚是不是没有遵循规范。

**Comment by ahwgs** [comment]
![image](https://user-images.githubusercontent.com/26664586/197317820-a2f85309-2a3e-4579-81bc-cf3c5096e8af.png)
![image](https://user-images.githubusercontent.com/26664586/197317825-aa551fb6-c72b-40bf-96b9-c11c9ba8d315.png)
试了下，是可以的哈
