### ISSUE TITLE
Receiving warning of deprecated options in this html-plugin

### ISSUE THREAD

**Issue by Mars-Interactive** [ahwgs/vite-plugin-html-config#11]
Hello,

I'm receiving these warnings when I run the dev server on **Vite** with your **vite-plugin-html-config** plugin:

> plugin 'html-plugin' uses deprecated 'enforce' option. Use 'order' option instead.
> plugin 'html-plugin' uses deprecated 'transform' option. Use 'handler' option instead.

**Comment by ahwgs** [comment]
This was brought on by the vite update, so I'll try to figure out how to fix it

**Comment by MikeLacroix** [comment]
Any updates on this?
