### ISSUE TITLE
能不能添加一个动态修改title的选项呢

### ISSUE THREAD

**Issue by AK47-dadada** [ahwgs/vite-plugin-html-config#3]

**Comment by ahwgs** [comment]
为什么要在构建里面动态修改title呢。直接在运行时修改不行吗
在路由钩子或者需要修改的地方去change

**Comment by AK47-dadada** [comment]
> 

因为打包的时候需要默认的title啊，不过我自己已经想办法处理了，但是还是建议提供一个可以修改title的option

**Comment by ahwgs** [comment]
哦哦。看到了，我以为之前我有提供过，后续会加上
