### ISSUE TITLE
请问能否开放transformIndexHtml的injectTo参数？

### ISSUE THREAD

**Issue by Kffhi** [ahwgs/vite-plugin-html-config#7]
例如vue2项目打包的时候，想把插入的<script>置于vue本身的<script type="module" crossorigin src="./assets/index.xxxxx.js"></script>之前，这个时候是否能使用head-prepend会更好一些
![image](https://user-images.githubusercontent.com/28257761/187579995-a3094e37-3b5a-4385-903f-8628dfac20d0.png)

**Comment by ahwgs** [comment]
> 例如vue2项目打包的时候，想把插入的<script>置于vue本身的<script type="module" crossorigin src="./assets/index.xxxxx.js"></script>之前，这个时候是否能使用head-prepend会更好一些 ![image](https://user-images.githubusercontent.com/28257761/187579995-a3094e37-3b5a-4385-903f-8628dfac20d0.png)

PR Welcome

**Comment by ahwgs** [comment]
> 例如vue2项目打包的时候，想把插入的<script>置于vue本身的<script type="module" crossorigin src="./assets/index.xxxxx.js"></script>之前，这个时候是否能使用head-prepend会更好一些 ![image](https://user-images.githubusercontent.com/28257761/187579995-a3094e37-3b5a-4385-903f-8628dfac20d0.png)

新版本已发
